//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _210512_WPF_App_Autokolcsonzo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoNyilvantartasDBEntities : DbContext
    {
        public AutoNyilvantartasDBEntities()
            : base("name=AutoNyilvantartasDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auto> Auto { get; set; }
        public virtual DbSet<Berlo> Berlo { get; set; }
        public virtual DbSet<Kolcsonzo> Kolcsonzo { get; set; }
    }
}
