//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _210512_WPF_App_Autokolcsonzo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Berlo
    {
        public int Id { get; set; }
        public string Nev { get; set; }
        public string Cim { get; set; }
        public string Nem { get; set; }
    
        public virtual Kolcsonzo Kolcsonzo { get; set; }
    }
}
