//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _210512_WPF_App_Autokolcsonzo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kolcsonzo
    {
        public int Id { get; set; }
        public string Nev { get; set; }
        public string Cim { get; set; }
        public Nullable<int> Auto_Id { get; set; }
        public Nullable<int> Berlo_Id { get; set; }
    
        public virtual Auto Auto { get; set; }
        public virtual Berlo Berlo { get; set; }
    }
}
